webtalk_init -webtalk_dir C:/Users/Daniele/Desktop/universit/elettronica digitale/vivado/Progetto_2/Progetto_2.sim/sim_1/synth/func/xsim/xsim.dir/Sim_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec  1 18:59:03 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a7bc8961-a09c-4803-b5f9-8939e5cf39a6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5ec5ef3936fa4a22987014df588e1963" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "28" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8164_KB" -context "xsim\\usage"
webtalk_transmit -clientid 489887629 -regid "" -xml C:/Users/Daniele/Desktop/universit/elettronica digitale/vivado/Progetto_2/Progetto_2.sim/sim_1/synth/func/xsim/xsim.dir/Sim_func_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Daniele/Desktop/universit/elettronica digitale/vivado/Progetto_2/Progetto_2.sim/sim_1/synth/func/xsim/xsim.dir/Sim_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Daniele/Desktop/universit/elettronica digitale/vivado/Progetto_2/Progetto_2.sim/sim_1/synth/func/xsim/xsim.dir/Sim_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
